stages:
  - build
  - deploy

build:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  stage: deploy
  image: node:20
  dependencies:
    - build
  script:
    - npm install -g wrangler
    - wrangler pages deploy ./dist --project-name="$CF_PROJECT_NAME" --branch=main

  only:
    - main
  environment:
    name: production
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
